main: thirtyvirus.template.TemplatePlugin
version: 1.0
name: HexiaPrestige
api-version: 1.12.2

commands:
  hexpres:
    description: Main command for HexiaPrestige. Use /hexpres help for more info
permissions:
  hexia.user:
    description: Allows player to use the plugin's user features
    default: true
  hexia.admin:
    description: Allows player to use the plugin's admin features
    default: op